Data Preprocessing Breast Cancer Dataset - 10/16/2026 - Lasgat0980

In [1]:
# Import necessary libraries
import pandas as pd
from datetime import datetime
from IPython.display import display, Markdown

todays_date = datetime.now().strftime("%Y-%m-%d")
student_id = "Lasgat0980"

# Load the Breast Cancer dataset
data = pd.read_csv(r'C:\Users\ldick\Downloads\breastCancerDataset.csv')

# Display the first few rows to understand what the data looks like
display(Markdown("### Step 1: Load the Dataset"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))
display(data.head())

### Step 1: Load the Dataset

Date: 2026-10-16

Student ID: Lasgat0980

,ID,Diagnosis,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
0,0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [2]:
display(Markdown("### Step 2: Initial Exploration of the Dataset"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Display dataset information
data.info()

# Display summary statistics
display(data.describe())

### Step 2: Initial Exploration of the Dataset

Date: 2026-10-16

Student ID: Lasgat0980

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  569 non-null    int64
 1   Diagnosis           569 non-null    str
 2   radius1             569 non-null    float64
 3   texture1            569 non-null    float64
 4   perimeter1          569 non-null    float64
 5   area1               569 non-null    float64
 6   smoothness1         569 non-null    float64
 7   compactness1        569 non-null    float64
 8   concavity1          569 non-null    float64
 9   concave_points1     569 non-null    float64
 10  symmetry1           569 non-null    float64
 11  fractal_dimension1  569 non-null    float64
 12  radius2             569 non-null    float64
 13  texture2            569 non-null    float64
 14  perimeter2          569 non-null    float64
 15  area2               569 non-null    float64
 16  smoothness2         569 non-null    float64
 17  compactness2        569 non-null    float64
 18  concavity2          569 non-null    float64
 19  concave_points2     569 non-null    float64
 20  symmetry2           569 non-null    float64
 21  fractal_dimension2  569 non-null    float64
 22  radius3             569 non-null    float64
 23  texture3            569 non-null    float64
 24  perimeter3          569 non-null    float64
 25  area3               569 non-null    float64
 26  smoothness3         569 non-null    float64
 27  compactness3        569 non-null    float64
 28  concavity3          569 non-null    float64
 29  concave_points3     569 non-null    float64
 30  symmetry3           569 non-null    float64
 31  fractal_dimension3  569 non-null    float64
dtypes: float64(30), int64(1), str(1)
memory usage: 142.9 KB

,ID,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,284.000000,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,164.400426,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,0.000000,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,142.000000,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,284.000000,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,426.000000,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,568.000000,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [3]:
display(Markdown("### Step 3: Check for Missing Values"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Check for missing values
print(data.isnull().sum())

### Step 3: Check for Missing Values

Date: 2026-10-16

Student ID: Lasgat0980

ID                    0
Diagnosis             0
radius1               0
texture1              0
perimeter1            0
area1                 0
smoothness1           0
compactness1          0
concavity1            0
concave_points1       0
symmetry1             0
fractal_dimension1    0
radius2               0
texture2              0
perimeter2            0
area2                 0
smoothness2           0
compactness2          0
concavity2            0
concave_points2       0
symmetry2             0
fractal_dimension2    0
radius3               0
texture3              0
perimeter3            0
area3                 0
smoothness3           0
compactness3          0
concavity3            0
concave_points3       0
symmetry3             0
fractal_dimension3    0
dtype: int64

In [4]:
display(Markdown("### Step 4: Check for Duplicate Rows"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Check for duplicate rows
print("Number of duplicate rows:", data.duplicated().sum())

# Remove duplicate rows
data.drop_duplicates(inplace=True)

# Verify duplicates have been removed
print("Number of duplicate rows after cleaning:", data.duplicated().sum())

### Step 4: Check for Duplicate Rows

Date: 2026-10-16

Student ID: Lasgat0980

Number of duplicate rows: 0
Number of duplicate rows after cleaning: 0

In [5]:
display(Markdown("### Step 5: Standardize Features"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Import StandardScaler
from sklearn.preprocessing import StandardScaler

# Standardize concavity1 and concavity3
scaler = StandardScaler()
data[['concavity1', 'concavity3']] = scaler.fit_transform(data[['concavity1', 'concavity3']])

# Display the standardized features
display(data[['concavity1', 'concavity3']].head())

### Step 5: Standardize Features

Date: 2026-10-16

Student ID: Lasgat0980

   concavity1  concavity3
0    2.652874    2.109526
1   -0.023846   -0.146749
2    1.363478    0.854974
3    1.915897    1.989588
4    1.371011    0.613179

In [6]:
display(Markdown("### Step 6: Split the Dataset"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Import train_test_split
from sklearn.model_selection import train_test_split

# Separate features and target variable
X = data.drop(columns=['ID', 'Diagnosis'])
y = data['Diagnosis']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Display the shapes of the training and testing sets
print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

### Step 6: Split the Dataset

Date: 2026-10-16

Student ID: Lasgat0980

Training set shape: (398, 30)
Testing set shape: (171, 30)

In [7]:
display(Markdown("### Step 7: Train and Evaluate the SVM Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Import necessary libraries
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Train the SVM model
svm_model = SVC()
svm_model.fit(X_train, y_train)

# Make predictions
y_pred_svm = svm_model.predict(X_test)

# Evaluate the model
print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print("SVM Classification Report:")
print(classification_report(y_test, y_pred_svm))

### Step 7: Train and Evaluate the SVM Model

Date: 2026-10-16

Student ID: Lasgat0980

SVM Accuracy: 0.935672514619883
SVM Classification Report:
              precision    recall  f1-score   support

           B       0.91      1.00      0.95       108
           M       1.00      0.83      0.90        63

    accuracy                           0.94       171
   macro avg       0.95      0.91      0.93       171
weighted avg       0.94      0.94      0.93       171

In [8]:
display(Markdown("### Step 8: Hyperparameter Tuning with GridSearchCV"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Import GridSearchCV
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly']
}

# Perform hyperparameter tuning
grid_search = GridSearchCV(SVC(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Display the best parameters
print("Best Parameters:", grid_search.best_params_)

# Make predictions using the best model
best_svm_model = grid_search.best_estimator_
y_pred_svm_tuned = best_svm_model.predict(X_test)

# Evaluate the tuned model
print("Tuned SVM Accuracy:", accuracy_score(y_test, y_pred_svm_tuned))
print("Tuned SVM Classification Report:")
print(classification_report(y_test, y_pred_svm_tuned))

### Step 8: Hyperparameter Tuning with GridSearchCV

Date: 2026-10-16

Student ID: Lasgat0980

Best Parameters: {'C': 10, 'kernel': 'linear'}
Tuned SVM Accuracy: 0.9707602339181286
Tuned SVM Classification Report:
              precision    recall  f1-score   support

           B       0.98      0.97      0.98       108
           M       0.95      0.97      0.96        63

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171

In [9]:
display(Markdown("### Step 9: Train and Evaluate the XGBoost Model"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Import necessary libraries
from xgboost import XGBClassifier

# Convert diagnosis labels to numerical values
y_train_xgb = y_train.map({'B': 0, 'M': 1})
y_test_xgb = y_test.map({'B': 0, 'M': 1})

# Train the XGBoost model
xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train_xgb)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate the model
print("XGBoost Accuracy:", accuracy_score(y_test_xgb, y_pred_xgb))
print("XGBoost Classification Report:")
print(classification_report(y_test_xgb, y_pred_xgb))

### Step 9: Train and Evaluate the XGBoost Model

Date: 2026-10-16

Student ID: Lasgat0980

XGBoost Accuracy: 0.9707602339181286
XGBoost Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       108
           1       0.95      0.97      0.96        63

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171

In [10]:
display(Markdown("### Step 10: Hyperparameter Tuning for XGBoost"))
display(Markdown(f"Date: {todays_date}"))
display(Markdown(f"Student ID: {student_id}"))

# Define the parameter grid
param_grid_xgb = {
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.2],
    'max_depth': [3, 4]
}

# Perform hyperparameter tuning
grid_search_xgb = GridSearchCV(XGBClassifier(random_state=42), param_grid_xgb, cv=5)
grid_search_xgb.fit(X_train, y_train_xgb)

# Display the best parameters
print("Best Parameters:", grid_search_xgb.best_params_)

# Make predictions using the best model
best_xgb_model = grid_search_xgb.best_estimator_
y_pred_xgb_tuned = best_xgb_model.predict(X_test)

# Evaluate the tuned model
print("Tuned XGBoost Accuracy:", accuracy_score(y_test_xgb, y_pred_xgb_tuned))
print("Tuned XGBoost Classification Report:")
print(classification_report(y_test_xgb, y_pred_xgb_tuned))

### Step 10: Hyperparameter Tuning for XGBoost

Date: 2026-10-16

Student ID: Lasgat0980

Best Parameters: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100}
Tuned XGBoost Accuracy: 0.9590643274853801
Tuned XGBoost Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.97      0.97       108
           1       0.95      0.94      0.94        63

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171

Bias could be introduced into the breast cancer dataset if it doesn't include enough patients from different ages, races, or backgrounds. This could cause the model to perform better for some groups than others. To reduce bias, it is important to use a diverse dataset, check for missing or incorrect data, and test the model on different groups of patients to make sure that all predictions are fair. 

The Tuned SVM performed better with an accuracy of 97.08%, compared to the tuned XGBoost model's 95.91%. The SVM also had a higher recall for malignant cases at 97% compared to the 94% for XGBoost. I think the SVM was the best choice for this dataset because it made fewer mistakes when it came to identifying malignant cases, which is really important when dealing with something like breast cancer.